assignment-rules:

  - project: chaotic-koala
    target: build
    configuration: staging
    runs-on:
      - linux-large-js

  - target: lint
    runs-on:
      - linux-medium-js

  - configuration: development
    runs-on:
      - linux-1
      - linux-2

  - target: unknown-task
    runs-on:
      - linux-unknown

  - project: chaotic-koala
    target: build
    configuration: staging
    runs-on:
      - linux-large-js

