distribute-on:
  default: 10 linux-medium-js, 5 linux-large-js, 1 linux-1

assignment-rules:
  - project: chaotic-koala
    target: build
    configuration: staging
    runs-on:
      - linux-large-js

  - target: lint
    runs-on:
      - linux-medium-js

  - configuration: development
    runs-on:
      - linux-1a
      - linux-2
      - linux-3
      - linux-medium-js
      - linux-large-js