assignment-rules:
  # Original Rules
  - project: chaotic-koala
    target: build
    configuration: staging
    runs-on:
      - linux-large-js

  - target: lint
    runs-on:
      - linux-medium-js

  - configuration: development
    runs-on:
      - linux-medium

  # Test Rule with Invalid Target
  - target: unknown-task
    runs-on:
      - linux-unknown

  # Overlapping Rules
  - project: chaotic-koala
    target: build
    configuration: staging
    runs-on:
      - linux-large-js

  - project: chaotic-koala
    target: build
    configuration: staging
    runs-on:
      - linux-medium
    priority: 1

  # Invalid Runs-On Value
  - target: build
    runs-on:
      - invalid-runner
