assignment-rules:
  # Rule with lower priority
  - project: chaotic-koala
    target: build
    configuration: staging
    runs-on:
      - linux-large-js
    priority: 0

  # Overlapping rule with higher priority
  - project: chaotic-koala
    target: build
    configuration: staging
    runs-on:
      - linux-medium
    priority: 1

  # Another overlapping rule without a priority field (should default to lower precedence)
  - project: chaotic-koala
    target: build
    configuration: staging
    runs-on:
      - linux-small
