name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # Reference the distribution configuration file
      - run: |
      # - run: npx nx-cloud start-ci-run --distribute-on=".nx/workflows/distribution-config.yaml" --stop-agents-after="build"
      - run: npx nx-cloud start-ci-run --assignment-rules=.nx/workflows/distribution-config.yaml --stop-agents-after="build"
      - run: npm ci --legacy-peer-deps

      # Run affected targets
      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected -t lint test build e2e-ci --configuration=staging