name: CI
on:
  push:
    branches:
      # Change this if your primary branch is not main
      - main
  pull_request:

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      # This line enables distribution
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"
      - run: npx nx-cloud start-ci-run --distribute-on=".nx/workflows/distribution-config.yaml" --stop-agents-after="e2e-ci"
      - run: npm ci --legacy-peer-deps

      - uses: nrwl/nx-set-shas@v4
      # Specify assignment rules
      - run: |
          echo "Setting assignment rules..."
          npx nx-cloud set-assignment-rules \
            --rules='[
              {
                "project": "chaotic-koala",
                "runsOn": ["linux-medium-js", "linux-large-js"]
              },
              {
                "target": "lint",
                "configuration": "production",
                "runsOn": ["linux-large-js"]
              },
              {
                "project": "lib1",
                "target": "test",
                "runsOn": ["linux-medium-js"]
              }
            ]'

      # Run affected targets
      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected -t lint test build e2e-ci --configuration=staging
      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected -t lint test build e2e-ci
