name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  main:
    name: Main Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Start CI Run
        run: npx nx-cloud start-ci-run --assignment-rules=".nx/workflows/distribution-config.yaml" --stop-agents-after="e2e-ci"

      - name: Run Format Check
        run: npx nx-cloud record -- nx format:check

      - name: Run Affected Targets
        run: npx nx affected -t lint test build e2e-ci --configuration=staging
